### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by DS1705** [SergeoLacruz/inventree-supplier-panel#1]
#[issue-1719469387](https://github.com/SergeoLacruz/inventree-supplier-plugin/issues/1#issue-1719469387)
sorry for the confusion i was in the wrong repository but i can not install the supplier panel
ModuleNotFoundError: No module named 'inventree_supplier'

**Comment by SergeoLacruz** [comment]
There seemed to be a bug in the setup file. I changed this. Surprisingly in installed well on my machine. Just give it a try. use the actual master branch.

**Comment by DS1705** [comment]
It works now the install was succes full

**Comment by DS1705** [comment]
i made a PO with supplier mouser but i do not see the panel
![image](https://github.com/SergeoLacruz/inventree-supplier-panel/assets/57893168/0aa06697-735d-4bfe-9cd9-25e7cc0aa04b)
`ValueError
Path:
/order/purchase-order/2/
Info:
invalid literal for int() with base 10: ''
When:
May 24, 2023, 8:56 a.m.
Data:
Traceback (most recent call last):

File "/home/dieter/src/InvenTree/plugin/views.py", line 26, in get_plugin_panels
panels += plug.render_panels(self, self.request, ctx)

File "/home/dieter/src/InvenTree/plugin/base/integration/mixins.py", line 712, in render_panels
for panel in self.get_custom_panels(view, request):

File "/home/dieter/env/lib/python3.8/site-packages/inventree_supplier_panel/supplier_panel.py", line 70, in get_custom_panels
SupplierPK=int(self.get_setting('MOUSER_PK'))

ValueError: invalid literal for int() with base 10: ''`

**Comment by SergeoLacruz** [comment]
Did you set the Mouser PK correctly in the settings of the plugin

**Comment by SergeoLacruz** [comment]
I reproduced this here. The PK is not set. I added an error handler for this case.
